image: ruby:2.4.2
stages:
  - build
  - test
  - review
  - stage
  - prod

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
  - cd reddit
  - bundle install

build_job:
  stage: build
  script:
    - echo 'Building'

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - echo 'Doing unit testing'
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Doing integration testing'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

deploy_staging:
  stage: stage
  when: manual
  script:
    - echo "Deploy to staging"
  environment:
    name: stage
    url: https://beta.example.com

deploy_production:
  stage: prod
  when: manual
  script:
    - echo "Deploy to prod"
  environment:
    name: prod
    url: https://example.com
