- name: install apt-key
  tags: install
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: D68FA50FEA312927

- name: add mongodb repository
  tags: install
  apt_repository:
    repo: "{{ mongo_repository }}"
  register: add_repo

- name: update cache
  tags: install
  apt: update_cache=yes
  when: mongo_update_cache_on_install or add_repo.changed

- name: install packages
  tags: install
  apt: 
    name: ['mongodb-org']
    state: latest
