- name: install apt-key
  tags: install
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: D68FA50FEA312927

- name: add mongodb repository
  tags: install
  apt_repository:
    repo: "{{ mongo_repository }}"

- name: update cache
  tags: install
  apt: update_cache=yes

- name: install packages
  tags: install
  apt: 
    name: ['mongodb-org']
    state: latest
