- name: Deploy app
  hosts: app
  gather_facts: False
  tasks:
  - name: clone application
    tags: deploy
    git:
      repo: "https://github.com/express42/reddit.git"
      dest: /home/{{ deploy_user }}/reddit
      version: monolith
    notify: reload puma
    
  - name: install bundler
    tags: deploy
    bundler:
      state: present
      chdir: /home/{{ deploy_user }}/reddit
    notify: reload puma
    changed_when: True

  - name: Print link
    tags: deploy
    debug:
      msg: "Puma: http://{{ ansible_host }}:9292/ Http: http://{{ ansible_host }}/"

  handlers:
  - name: reload puma
    become: True
    systemd: name=puma state=restarted
