- name: Deploy app
  hosts: app
  gather_facts: False
  tasks:
  - name: clone application
    git:
      repo: "https://github.com/express42/reddit.git"
      dest: /home/appuser/reddit
      version: monolith
    notify: reload puma
    
  - name: install bundler
    bundler:
      state: present
      chdir: /home/appuser/reddit
    notify: reload puma
    changed_when: True

  - name: Print link
    debug:
      msg: "App: http://{{ ansible_host }}:9292/"

  handlers:
  - name: reload puma
    become: True
    systemd: name=puma state=restarted
