---
- name: Provisioner for ruby app
  hosts: all
  become: True
  gather_facts: False
  roles:
  - name: app

  tasks:
  - debug:
      var: install_log['stdout_lines']

  - debug:
      var: install_log['stderr_lines']
