---
- name: Provisioner for mongodb
  hosts: all
  become: True
  gather_facts: False
  roles:
  - name: db
    mongo_repository: "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse"

  tasks:
  - debug:
      var: install_log['stdout_lines']

  - debug:
      var: install_log['stderr_lines']
