---
# tasks file for app
- name: Add unit file for puma
  become: True
  copy:
    src: puma.service
    dest: /etc/systemd/system/puma.service
  notify: reload puma

- name: get actual local db address from temp var if exists
  set_fact:
    db_host: "{{ hostvars['dummy_host']['db_ip'] }}"
  when: hostvars['dummy_host'] is defined and hostvars['dummy_host']['db_ip'] is defined

- name: Display configured db address
  debug:
    msg: "DB IP: {{ db_host }}"

- name: Add db ip address to app config
  template:
    src: db_config.j2
    dest: /home/appuser/db_config
  notify: reload puma

- name: Systemd enable puma
  become: True
  systemd: name=puma enabled=yes
