
- name: Add unit file for puma
  become: True
  tags: install
  template:
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service
  notify: reload puma

- name: get actual local db address from temp var if exists
  tags: install
  set_fact:
    db_host: "{{ hostvars['dummy_host']['db_ip'] }}"
  when: hostvars['dummy_host'] is defined and hostvars['dummy_host']['db_ip'] is defined

- name: Display configured db address
  tags: install
  debug:
    msg: "DB IP: {{ db_host }}"

- name: Add db ip address to app config
  tags: config
  template:
    src: db_config.j2
    dest: /home/{{ deploy_user }}/db_config
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
  notify: reload puma

- name: Systemd enable puma
  tags: install config
  become: True
  systemd: name=puma enabled=yes
