- name: update cache
  tags: install
  apt: update_cache=yes

- name: install packages
  tags: install
  apt: 
    name: ['ruby-full', 'ruby-bundler', 'build-essential']
    state: latest
  register: install_log
