---
- name: Gitlab provision
  hosts: gitlab
  vars:
    gitlab_user: appuser
  roles:
  - name: docker-ubuntu
    become: True
    docker_ubuntu_version: xenial

  tasks:
  - debug:
      msg: Do not forget to specify gitlab host via '-e gitlab_external_ip=x.x.x.x'!

  - name: Make necessary dirs for gitlab container
    become: True
    file:
      path: "{{ item }}"
      state: directory
      owner: "{{ gitlab_user }}"
    with_items:
    - /srv/gitlab/config
    - /srv/gitlab/data
    - /srv/gitlab/logs

  - name: Add docker-compose file
    template:
      src: ../templates/docker-compose.yml.j2
      dest: /srv/gitlab/docker-compose.yml
      owner: "{{ gitlab_user }}"

  - name: Allow {{ gitlab_user }} to run docker
    become: True
    user:
      name: "{{ gitlab_user }}"
      append: True
      groups: 
      - docker

  - name: Restart docker service
    become: True
    service: 
      name: docker
      state: restarted
