---
- name: Provisioner for mongodb
  hosts: all
  become: True
  gather_facts: False
  vars:
    mongo_repository: "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse"
  tasks:
  - name: install apt-key
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: D68FA50FEA312927

  - name: add mongodb repository
    apt_repository:
      repo: "{{ mongo_repository }}"

  - name: update cache
    apt: update_cache=yes

  - name: install packages
    apt: 
      name: ['mongodb-org']
      state: latest
    register: install_log

  - debug:
      var: install_log['stdout_lines']

  - debug:
      var: install_log['stderr_lines']
