Vagrant.configure("2") do |config|

    config.vm.provider:libvirt do |v|
        v.memory=512
        v.cpus=2
        #v.connect_via_ssh = "true"
    end

    config.vm.define "dbserver" do |db|
        db.vm.box = "nrclark/xenial64-minimal-libvirt"
        db.vm.hostname = "dbserver"
        db.vm.network :private_network, ip: "10.10.10.10" #, :libvirt__forward_mode => "route"

        db.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbooks/site.yml"
            ansible.groups = {
                "db" => ["dbserver"]
            }        
        end
    end

    config.vm.define "appserver" do |app|
        app.vm.box = "nrclark/xenial64-minimal-libvirt"
        app.vm.hostname = "appserver"
        app.vm.network :private_network, ip: "10.10.10.20" #, :libvirt__forward_mode => "route"
    end
end
