Vagrant.configure("2") do |config|

    config.vm.provider:virtualbox do |v|
        v.memory=512
        v.cpus=2
    end

    config.vm.define "dbserver" do |db|
        db.vm.box = "ubuntu/xenial64"
        db.vm.hostname = "dbserver"
        db.vm.network :private_network, ip: "10.10.10.10"

        db.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbooks/site.yml"
            ansible.groups = {
                "db" => ["dbserver"]
            }        
        end
    end

    config.vm.define "appserver" do |app|
        app.vm.box = "ubuntu/xenial64"
        app.vm.hostname = "appserver"
        app.vm.network :private_network, ip: "10.10.10.20"

        app.vm.provision "ansible" do |ansible|
            ansible.playbook = "playbooks/site.yml"
            ansible.groups = {
                "app" => ["appserver"]
            }        
            ansible.extra_vars = {
                "deploy_user" => "vagrant",
                "db_host" => "10.10.10.10",
                "ansible_selinux" => { "status": "disabled"},
                "ansible_distribution" => "Ubuntu",
                "ansible_os_family" => "Debian",
            }
        end
    end
end
